[package]
name = "projectpadsql"
version = "0.0.1"
authors = [ "Emmanuel Touzery" ]
edition = "2018"

[dependencies]
dirs = "3.0.1"
keyring = "0.10.0"
diesel = { version = "1.4.5", features = ["sqlite"] }
# want the same version as diesel...
# https://github.com/diesel-rs/diesel/blob/master/diesel/Cargo.toml
libsqlite3-sys = { version =  "0.18.0", features = ["sqlcipher"] }
strum = "0.19.5"
strum_macros = "0.19.4"
chrono = "0.4.19"
