[package]
name = "projectpad"
version = "0.1.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

[build-dependencies]
reqwest = { version = "0.10.6", features = ["blocking"] }
flate2 = "1.0.16"
tar = "0.4.29"

[dependencies]
relm = "0.20.0"
relm-derive = "0.20.0"
glib = "0.10.1"
gio = "0.9.0"
cairo-rs = { version = "0.9.1", features = ["png"] }
gdk = "0.13.0"
projectpadsql = { path = "../projectpadsql" }
diesel = { version = "1.4.5", features = ["sqlite"] }
pango = "0.9.0"

[dependencies.gtk]
version = "0.9.0"
features = ["v3_22_29"]
