[package]
name = "projectpad"
version = "0.1.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

[dependencies]
relm = "0.19.0"
relm-derive = "0.19.0"
gtk = "0.8.1"
cairo-rs = {version = "0.8.1", features = ["png"]}
gdk = "0.12.1"
projectpadsql = { path = "../projectpadsql" }
diesel = {version = "1.4.4", features= ["sqlite"]}
itertools = "0.9.0"
