[package]
name = "projectpad"
version = "0.1.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

[build-dependencies]
reqwest = {version="0.10.6", features=["blocking"]}
flate2 = "1.0"
tar = "0.4"

[dependencies]
relm = "0.19.0"
relm-derive = "0.19.0"
glib = "0.9.3"
gio = "0.8.1"
cairo-rs = {version = "0.8.1", features = ["png"]}
gdk = "0.12.1"
projectpadsql = { path = "../projectpadsql" }
diesel = {version = "1.4.4", features= ["sqlite"]}
pango = "0.8.0"
pangocairo-sys="0.10.1"

[dependencies.gtk]
version = "0.8.1"
features = ["v3_22_29"]
